export type MainstreamProduct = {
  id: string;
  name: string;
  company: string;
  productUrl: string;
  sourceUrl: string;
  category: string;
  tagline: string;
  bestFor: string;
  productShape: string;
  entryModel: string;
  accent: string;
};

export type IndieProduct = {
  id: string;
  name: string;
  maker: string;
  origin: string;
  productUrl: string;
  sourceUrl: string;
  category: string;
  tagline: string;
  bestFor: string;
  teamLabel: string;
  businessModel: string;
  globalSignal: string;
  accent: string;
};

export const GLOBAL_PRODUCTS_LAST_VERIFIED = "2026-08-04";

export const MAINSTREAM_AI_PRODUCTS: readonly MainstreamProduct[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    company: "OpenAI",
    productUrl: "https://chatgpt.com/",
    sourceUrl: "https://chatgpt.com/overview/",
    category: "通用 AI 助手",
    tagline: "把写作、研究、编程、图像和文件分析收进同一个对话入口。",
    bestFor: "个人到企业的通用工作流",
    productShape: "一个入口，多种任务",
    entryModel: "免费入口 · 个人与团队订阅",
    accent: "#10a37f",
  },
  {
    id: "claude",
    name: "Claude",
    company: "Anthropic",
    productUrl: "https://claude.ai",
    sourceUrl: "https://claude.com/product/overview",
    category: "思考与创作",
    tagline: "围绕长文档、复杂推理、写作和代码建立清晰的协作体验。",
    bestFor: "知识工作与复杂任务",
    productShape: "对话 + 项目 + 工具连接",
    entryModel: "免费入口 · 个人与组织订阅",
    accent: "#d97757",
  },
  {
    id: "gemini",
    name: "Gemini",
    company: "Google",
    productUrl: "https://gemini.google.com",
    sourceUrl: "https://gemini.google/overview/",
    category: "多模态助手",
    tagline: "把搜索、深度研究与 Google 应用连接到统一的多模态体验。",
    bestFor: "Google 生态内的工作与学习",
    productShape: "助手 + 搜索 + 生态连接",
    entryModel: "免费入口 · 高级订阅",
    accent: "#4f7df3",
  },
  {
    id: "microsoft-copilot",
    name: "Microsoft Copilot",
    company: "Microsoft",
    productUrl: "https://copilot.microsoft.com",
    sourceUrl: "https://www.microsoft.com/en-us/microsoft-copilot/for-individuals/",
    category: "办公 AI",
    tagline: "从独立助手延伸到 Windows 与 Microsoft 365 的日常工作场景。",
    bestFor: "办公、搜索与企业协作",
    productShape: "助手 + 操作系统 + 办公套件",
    entryModel: "免费入口 · 个人与企业方案",
    accent: "#6b57d2",
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly",
    company: "Adobe",
    productUrl: "https://firefly.adobe.com/",
    sourceUrl: "https://www.adobe.com/products/firefly.html",
    category: "生成式创意",
    tagline: "生成并编辑图像、视频、音频和矢量内容，再接入专业创作流程。",
    bestFor: "品牌、营销与专业创作者",
    productShape: "生成器 + 编辑器 + Creative Cloud",
    entryModel: "免费层 · 生成点数与订阅",
    accent: "#e43b55",
  },
  {
    id: "canva-magic-studio",
    name: "Canva AI",
    company: "Canva",
    productUrl: "https://www.canva.com/canva-ai/",
    sourceUrl: "https://www.canva.com/canva-ai/",
    category: "AI 设计与内容创作",
    tagline: "用模板、品牌资产和 AI 把设计、改写、翻译与多渠道发布连起来。",
    bestFor: "非设计师与增长团队",
    productShape: "AI 能力嵌入完整编辑器",
    entryModel: "免费入口 · 个人与团队订阅",
    accent: "#7b61ff",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    company: "Perplexity AI",
    productUrl: "https://www.perplexity.ai/",
    sourceUrl: "https://www.perplexity.ai/hub",
    category: "AI 搜索与研究",
    tagline: "以实时网络为基础组织答案、标注来源，并把追问和深度研究放进同一条检索路径。",
    bestFor: "检索、研究与事实核验",
    productShape: "答案引擎 + 深度研究 + API",
    entryModel: "免费入口 · Pro 与企业订阅",
    accent: "#1f8f85",
  },
  {
    id: "runway",
    name: "Runway",
    company: "Runway",
    productUrl: "https://runwayml.com/",
    sourceUrl: "https://runwayml.com/product/ai-video-generator",
    category: "AI 视频创作",
    tagline: "从文本、图片或现有片段生成、编辑并延展视频，把模型选择和精修工具收进工作台。",
    bestFor: "视频创作者、品牌与制作团队",
    productShape: "生成 + 精修 + 工作流",
    entryModel: "免费试用 · 点数与订阅",
    accent: "#6f4df6",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    company: "ElevenLabs",
    productUrl: "https://elevenlabs.io/",
    sourceUrl: "https://elevenlabs.io/",
    category: "AI 语音与音频",
    tagline: "为创作者、企业和开发者提供多语言语音生成、声音克隆与对话式语音 Agent。",
    bestFor: "配音、本地化与语音 Agent",
    productShape: "创作套件 + Agent + API",
    entryModel: "免费入口 · 订阅与 API 用量",
    accent: "#111111",
  },
  {
    id: "cursor",
    name: "Cursor",
    company: "Anysphere",
    productUrl: "https://www.cursor.com/",
    sourceUrl: "https://www.cursor.com/features",
    category: "AI 编程",
    tagline: "把代码库理解、自然语言修改、智能补全与可自主执行任务的 Agent 合进编辑器。",
    bestFor: "个人开发者与工程团队",
    productShape: "编辑器 + Agent + 代码库上下文",
    entryModel: "免费入口 · 个人与团队订阅",
    accent: "#262626",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    company: "Midjourney",
    productUrl: "https://www.midjourney.com/",
    sourceUrl: "https://docs.midjourney.com/hc/en-us/articles/32764383466893-Editor",
    category: "AI 图像与视觉",
    tagline: "围绕高质量图像生成、风格探索与可控编辑，建立面向视觉创作者的完整工作流。",
    bestFor: "视觉概念、品牌创意与插画",
    productShape: "生成 + 社区探索 + 编辑器",
    entryModel: "订阅制",
    accent: "#4b45e6",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    company: "Notion",
    productUrl: "https://www.notion.com/product/ai",
    sourceUrl: "https://www.notion.com/help/notion-ai-faqs",
    category: "AI 知识工作",
    tagline: "在文档、知识库、项目与会议记录中完成跨应用检索、写作、总结和深度研究。",
    bestFor: "团队知识、项目协作与会议",
    productShape: "工作空间 + 企业搜索 + Agent",
    entryModel: "随商业与企业方案提供",
    accent: "#2f3437",
  },
  {
    id: "deepl",
    name: "DeepL",
    company: "DeepL",
    productUrl: "https://www.deepl.com/",
    sourceUrl: "https://www.deepl.com/en/products-overview",
    category: "语言 AI",
    tagline: "把文本、文档、语音与写作辅助组织成面向个人、开发者和企业的多语言产品矩阵。",
    bestFor: "跨语言沟通、本地化与全球团队",
    productShape: "翻译器 + 写作 + 语音 + API",
    entryModel: "免费入口 · Pro、API 与企业方案",
    accent: "#0f2b46",
  },
  {
    id: "synthesia",
    name: "Synthesia",
    company: "Synthesia",
    productUrl: "https://www.synthesia.io/",
    sourceUrl: "https://www.synthesia.io/",
    category: "AI 数字人视频",
    tagline: "用数字人、AI 配音和一键翻译制作企业视频，并覆盖从创作到协作发布的完整流程。",
    bestFor: "培训、销售赋能与企业内容",
    productShape: "数字人 + 视频编辑 + 多语言发布",
    entryModel: "免费入口 · 个人与企业订阅",
    accent: "#6548d7",
  },
  {
    id: "gamma",
    name: "Gamma",
    company: "Gamma",
    productUrl: "https://gamma.app/",
    sourceUrl: "https://gamma.app/",
    category: "AI 演示与设计",
    tagline: "从提示词或大纲生成演示、网页、文档与社交素材，再用 AI 快速改版和适配品牌。",
    bestFor: "提案、教学、营销与轻量网站",
    productShape: "生成式画布 + 编辑器 + 发布",
    entryModel: "免费入口 · 个人与团队订阅",
    accent: "#8b5cf6",
  },
  {
    id: "lovable",
    name: "Lovable",
    company: "Lovable",
    productUrl: "https://lovable.dev/",
    sourceUrl: "https://lovable.dev/",
    category: "AI 应用开发",
    tagline: "通过自然语言、截图和文档生成可工作的应用与网站，并继续在对话中迭代和发布。",
    bestFor: "创业者、产品经理与非技术团队",
    productShape: "对话生成 + 可视化迭代 + 部署",
    entryModel: "免费入口 · 个人与企业订阅",
    accent: "#ea4b71",
  },
  {
    id: "mindstudio",
    name: "MindStudio",
    company: "MindStudio",
    productUrl: "https://www.mindstudio.ai/",
    sourceUrl: "https://www.mindstudio.ai/",
    category: "AI Agent 构建",
    tagline: "用无代码画布、模型与集成搭建可推理、调用工具并跨步骤执行任务的 AI Agent。",
    bestFor: "业务自动化、内部工具与 Agent 产品",
    productShape: "Agent 画布 + 模型路由 + 集成",
    entryModel: "免费入口 · 团队与企业方案",
    accent: "#6558ff",
  },
  {
    id: "renderforest",
    name: "Renderforest",
    company: "Renderforest",
    productUrl: "https://www.renderforest.com/",
    sourceUrl: "https://www.renderforest.com/subscription/",
    category: "AI 视频与品牌创作",
    tagline: "把 AI 视频、图像、配音、设计与品牌素材放进一个面向个人和团队的在线创作平台。",
    bestFor: "营销视频、品牌内容与轻量设计",
    productShape: "生成器 + 编辑器 + 素材库",
    entryModel: "免费入口 · 点数与个人、团队订阅",
    accent: "#6c5ce7",
  },
  {
    id: "replit",
    name: "Replit",
    company: "Replit",
    productUrl: "https://replit.com/",
    sourceUrl: "https://replit.com/pricing",
    category: "AI 应用开发",
    tagline: "从自然语言描述出发生成、迭代并发布 Web、移动端和业务应用，内置数据库、托管与集成。",
    bestFor: "创业者、产品团队与快速原型",
    productShape: "Agent + 全栈运行时 + 发布",
    entryModel: "免费入口 · 个人、专业与企业方案",
    accent: "#f26207",
  },
  {
    id: "heygen",
    name: "HeyGen",
    company: "HeyGen",
    productUrl: "https://www.heygen.com/",
    sourceUrl: "https://www.heygen.com/",
    category: "AI 数字人视频",
    tagline: "用数字人、脚本和视频 Agent 生成完整视频，并以口型同步和声音克隆完成跨语言本地化。",
    bestFor: "营销、培训、课程与全球化内容",
    productShape: "数字人 + 视频 Agent + 翻译",
    entryModel: "免费入口 · 创作者、团队与企业订阅",
    accent: "#4f46e5",
  },
  {
    id: "kling-ai",
    name: "Kling AI",
    company: "Kuaishou",
    productUrl: "https://kling.ai/",
    sourceUrl: "https://kling.ai/",
    category: "AI 视频与图像",
    tagline: "从文本或图片生成高质量视频和视觉素材，并提供动作、镜头与多模态编辑能力。",
    bestFor: "短片、广告、视觉概念与创意制作",
    productShape: "视频生成 + 图像生成 + 编辑",
    entryModel: "免费入口 · 点数与订阅",
    accent: "#111827",
  },
  {
    id: "devin",
    name: "Devin",
    company: "Cognition",
    productUrl: "https://devin.ai/",
    sourceUrl: "https://devin.ai/",
    category: "AI 软件工程",
    tagline: "在隔离开发环境中理解代码库、规划任务、编写与测试代码，并把结果交付为可审查的变更。",
    bestFor: "工程任务、迁移、修复与团队并行开发",
    productShape: "工程 Agent + 云端工作区 + 协作",
    entryModel: "个人入口 · 团队与企业方案",
    accent: "#7c3aed",
  },
  {
    id: "retool",
    name: "Retool",
    company: "Retool",
    productUrl: "https://retool.com/",
    sourceUrl: "https://retool.com/",
    category: "AI 内部工具",
    tagline: "通过提示词生成连接真实业务数据的内部应用，并把权限、审计、工作流和企业治理一并交付。",
    bestFor: "运营、数据、IT 与企业应用团队",
    productShape: "AI App Builder + 数据连接 + 治理",
    entryModel: "免费入口 · 团队与企业订阅",
    accent: "#3b82f6",
  },
  {
    id: "magic-hour",
    name: "Magic Hour",
    company: "Magic Hour",
    productUrl: "https://magichour.ai/",
    sourceUrl: "https://magichour.ai/",
    category: "AI 视觉创作",
    tagline: "在一个浏览器工作台中完成视频、图像、换脸、口型同步、配音与批量视觉 API 工作流。",
    bestFor: "创作者、营销、电商与开发者",
    productShape: "100+ 创作工具 + 模型聚合 + API",
    entryModel: "免注册试用 · 免费点数与订阅",
    accent: "#e5489b",
  },
] as const;

export const INDIE_AI_PRODUCTS: readonly IndieProduct[] = [
  {
    id: "photo-ai",
    name: "Photo AI",
    maker: "Pieter Levels",
    origin: "荷兰创始人 · 全球在线交付",
    productUrl: "https://photoai.com",
    sourceUrl: "https://photoai.com/faq/who-created-photo-ai-meet-pieter-levels-the-founder-5465077",
    category: "AI 人像与视觉",
    tagline: "不靠摄影棚，在线生成个人写真、商品试穿与创作者视觉素材。",
    bestFor: "创作者、电商与个人品牌",
    teamLabel: "1 人独立运营",
    businessModel: "订阅 + 点数",
    globalSignal: "英文官网 · 在线自助购买",
    accent: "#e34b5f",
  },
  {
    id: "boltai",
    name: "BoltAI",
    maker: "Daniel Nguyen",
    origin: "Daniel Nguyen 创办 · 全球 Mac 用户",
    productUrl: "https://boltai.com",
    sourceUrl: "https://boltai.com/about",
    category: "桌面 AI 客户端",
    tagline: "把多家模型、本地文件与快捷指令放进原生 Mac 工作流。",
    bestFor: "开发者与重度 Mac 用户",
    teamLabel: "独立创始人主导",
    businessModel: "授权 + BYOK",
    globalSignal: "英文产品 · 本地优先 · 全球交付",
    accent: "#3478f6",
  },
  {
    id: "audiopen",
    name: "AudioPen",
    maker: "Louis Pereira",
    origin: "Louis Pereira 创办 · 多端全球产品",
    productUrl: "https://www.audiopen.ai",
    sourceUrl: "https://www.audiopen.ai/faq",
    category: "语音写作",
    tagline: "把随口说出的想法整理成结构清楚、保留个人语气的文字。",
    bestFor: "写作者、顾问与知识工作者",
    teamLabel: "独立创始人主导",
    businessModel: "免费层 + Prime 授权",
    globalSignal: "多语言 · Web、移动端与桌面端",
    accent: "#9a63e8",
  },
  {
    id: "orshot",
    name: "Orshot",
    maker: "Rishi Mohan",
    origin: "Rishi Mohan · 德国柏林",
    productUrl: "https://orshot.com",
    sourceUrl: "https://orshot.com/about",
    category: "视觉自动化 API",
    tagline: "设计一次模板，再通过 API、无代码工具或 Agent 批量生成品牌素材。",
    bestFor: "开发者、代理商与营销团队",
    teamLabel: "1 人构建 · 小规模运营",
    businessModel: "用量订阅",
    globalSignal: "API-first · 英文文档 · 全球 B2B",
    accent: "#ef8c2f",
  },
  {
    id: "typingmind",
    name: "TypingMind",
    maker: "Tony Dinh 创办 · TypingMind 团队",
    origin: "越南创始团队 · 全球用户",
    productUrl: "https://www.typingmind.com",
    sourceUrl: "https://news.tonydinh.com/p/jun-2023-how-i-work-with-employees",
    category: "多模型 AI 工作台",
    tagline: "用自己的 API Key 连接多家模型，并加入角色、插件与团队能力。",
    bestFor: "AI 重度用户与小团队",
    teamLabel: "创始人主导的小团队",
    businessModel: "个人授权 + 团队订阅 + BYOK",
    globalSignal: "英文产品 · 多模型 · 自助交付",
    accent: "#2f855a",
  },
  {
    id: "sitegpt",
    name: "SiteGPT",
    maker: "Bhanu Teja 与 Sai Dheeraj",
    origin: "印度创始团队 · 全球 B2B",
    productUrl: "https://sitegpt.ai",
    sourceUrl: "https://sitegpt.ai/blog/authors",
    category: "AI 客服与获客",
    tagline: "从网站和知识库训练客服助手，嵌入站点回答问题并承接线索。",
    bestFor: "SaaS、服务商与内容型网站",
    teamLabel: "两位联合创始人主导",
    businessModel: "B2B 订阅",
    globalSignal: "95+ 语言 · 自助嵌入 · 全球客户",
    accent: "#15a176",
  },
  {
    id: "interior-ai",
    name: "Interior AI",
    maker: "Pieter Levels",
    origin: "荷兰独立创始人 · 全球在线交付",
    productUrl: "https://interiorai.com/",
    sourceUrl: "https://interiorai.com/faq/who-built-and-is-behind-interior-ai-9570846",
    category: "AI 室内设计",
    tagline: "上传房间照片，快速生成不同风格的室内改造、虚拟软装和房产展示图。",
    bestFor: "房产、室内设计与家居用户",
    teamLabel: "1 人独立运营",
    businessModel: "订阅 + 点数",
    globalSignal: "英文产品 · 在线自助生成",
    accent: "#b7791f",
  },
  {
    id: "macwhisper",
    name: "MacWhisper",
    maker: "Jordi Bruin 与 Good Snooze",
    origin: "荷兰小团队 · 全球 Mac 用户",
    productUrl: "https://www.macwhisper.com/",
    sourceUrl: "https://www.macwhisper.com/",
    category: "本地 AI 转录",
    tagline: "在 Mac 本地完成音视频转录、会议记录和系统级语音输入，兼顾多语言与隐私。",
    bestFor: "研究者、创作者与会议场景",
    teamLabel: "创始人主导的小团队",
    businessModel: "免费层 + Pro 授权",
    globalSignal: "100+ 语言 · 本地模型 · 全球交付",
    accent: "#2463eb",
  },
  {
    id: "formula-bot",
    name: "Formula Bot",
    maker: "David Bressler",
    origin: "美国独立创始人 · 全球数据用户",
    productUrl: "https://www.formulabot.com/",
    sourceUrl: "https://www.indiehackers.com/post/8XGnzrxG1neA3jy37x2D",
    category: "AI 数据分析",
    tagline: "用自然语言分析表格、CSV、数据库和文档，生成图表、公式与可复用的数据流程。",
    bestFor: "运营、财务与数据分析者",
    teamLabel: "独立创始人主导",
    businessModel: "免费层 + 订阅",
    globalSignal: "英文产品 · 自助分析 · 多数据源",
    accent: "#19a974",
  },
  {
    id: "elephas",
    name: "Elephas",
    maker: "Kamban S 与 Ayush Chaturvedi",
    origin: "印度创始团队 · 全球 Mac 用户",
    productUrl: "https://elephas.app/",
    sourceUrl: "https://elephas.app/about",
    category: "个人知识库",
    tagline: "在 Mac 本地索引文件、PDF 和笔记，建立可检索、可对话的个人知识工作空间。",
    bestFor: "专业人士、研究与个人知识管理",
    teamLabel: "两人自筹团队",
    businessModel: "订阅 + 终身授权",
    globalSignal: "英文产品 · 本地优先 · 全球交付",
    accent: "#805ad5",
  },
  {
    id: "recast-studio",
    name: "Recast Studio",
    maker: "Abhinav Sohani 与小团队",
    origin: "印度自筹团队 · 全球创作者",
    productUrl: "https://recast.studio/",
    sourceUrl: "https://in.linkedin.com/company/recaststudio",
    category: "AI 视频再利用",
    tagline: "从长视频中自动寻找高光、生成字幕与短片，并适配不同社交平台的画幅和分发。",
    bestFor: "播客、访谈与内容营销团队",
    teamLabel: "2–10 人小团队",
    businessModel: "免费试用 + 订阅",
    globalSignal: "英文产品 · 自助剪辑 · 多平台输出",
    accent: "#e85d75",
  },
  {
    id: "pdf-ai",
    name: "PDF.ai",
    maker: "Damon Chen",
    origin: "独立创始人 · 全球文档用户",
    productUrl: "https://pdf.ai/",
    sourceUrl: "https://www.indiehackers.com/post/11-solo-indie-hackers-making-1m-in-annual-revenue-NRq6hCm3La6N6UliFRfE",
    category: "AI 文档问答",
    tagline: "让用户直接与 PDF 对话，并把文档解析、字段提取和智能拆分能力接入工作流。",
    bestFor: "研究、法务、教育与文档自动化",
    teamLabel: "独立创始人 · 零员工",
    businessModel: "免费层 + 订阅 + API",
    globalSignal: "英文产品 · Web + API · 全球交付",
    accent: "#ff5b4d",
  },
  {
    id: "headshotpro",
    name: "HeadshotPro",
    maker: "Danny Postma 与小型远程团队",
    origin: "荷兰创办 · 全球个人与企业用户",
    productUrl: "https://www.headshotpro.com/",
    sourceUrl: "https://www.indiehackers.com/post/planning-to-expand-team-from-4-to-6-Wv11tRMvyzmMPOAGPgp3",
    category: "AI 商务头像",
    tagline: "用少量自拍生成可用于 LinkedIn、公司网站和团队名录的专业商务头像。",
    bestFor: "求职者、顾问与分布式团队",
    teamLabel: "独立公司 · 小型远程团队",
    businessModel: "按次购买 + 团队套餐",
    globalSignal: "英文产品 · 全球自助购买 · 企业入口",
    accent: "#c2415d",
  },
  {
    id: "podsqueeze",
    name: "Podsqueeze",
    maker: "Tiago 与 João",
    origin: "两位联合创始人 · 全球播客用户",
    productUrl: "https://podsqueeze.com/",
    sourceUrl: "https://podsqueeze.com/",
    category: "AI 播客再利用",
    tagline: "把播客和长视频自动转成文字稿、节目笔记、短视频、博客与社交平台素材。",
    bestFor: "播客主、内容团队与代理商",
    teamLabel: "两位联合创始人主导",
    businessModel: "免费入口 + 订阅",
    globalSignal: "英文产品 · 多语言内容 · 全球创作者",
    accent: "#f97316",
  },
  {
    id: "swan-ai",
    name: "Swan",
    maker: "Amos Bar-Joseph、Ido Goldberg、Niv Oppenhaim",
    origin: "三位联合创始人 · 全球 B2B",
    productUrl: "https://www.getswan.com/",
    sourceUrl: "https://www.getswan.com/about",
    category: "AI GTM 工程师",
    tagline: "用自然语言搭建获客、线索评分、数据丰富和 CRM 流程，让小团队运行完整 GTM 系统。",
    bestFor: "销售、市场与 RevOps 团队",
    teamLabel: "3 位联合创始人运营",
    businessModel: "免费试用 + B2B 订阅",
    globalSignal: "英文产品 · 全球 B2B · 自助试用",
    accent: "#c2410c",
  },
  {
    id: "ninjapear",
    name: "NinjaPear",
    maker: "Steven Goh",
    origin: "新加坡独立创始人 · 全球 B2B",
    productUrl: "https://nubela.co/",
    sourceUrl: "https://nubela.co/blog/how-im-building-a-1m-arr-venture-with-ai-as-a-bootstrapped-solo-founder-15k-revenue-last-mo-10m-last-exit-w-proxycurl/",
    category: "AI 原生 B2B 数据",
    tagline: "为销售、竞争研究和 AI Agent 提供实时公司与人物数据、监控能力以及可编程 API。",
    bestFor: "开发者、GTM 与竞争情报团队",
    teamLabel: "1 人独立运营",
    businessModel: "免费试用 + 按量付费",
    globalSignal: "多语言官网 · API-first · 全球交付",
    accent: "#0f766e",
  },
  {
    id: "my-askai",
    name: "My AskAI",
    maker: "Alex Rainey 与 Mike Heap",
    origin: "两位联合创始人 · 全球 B2B",
    productUrl: "https://myaskai.com/",
    sourceUrl: "https://myaskai.com/about-us",
    category: "AI 客户支持",
    tagline: "接入现有帮助台，用企业知识和历史工单回答问题、自动学习，并按规则执行支持任务。",
    bestFor: "SaaS、电商与精简客服团队",
    teamLabel: "2 位联合创始人运营",
    businessModel: "30 天免费试用 + 订阅与用量",
    globalSignal: "95 种语言 · 五大帮助台 · 全球客户",
    accent: "#5b5bd6",
  },
  {
    id: "subscribr",
    name: "Subscribr",
    maker: "Gil Hildebrand",
    origin: "独立创始人主导 · 全球 YouTube 创作者",
    productUrl: "https://subscribr.ai/",
    sourceUrl: "https://subscribr.ai/about",
    category: "AI 视频脚本",
    tagline: "围绕频道定位、选题研究和结构化写作生成 YouTube 脚本，并在编辑器中继续打磨。",
    bestFor: "YouTube 创作者、频道团队与代运营",
    teamLabel: "独立创始人主导",
    businessModel: "订阅 + AI 点数",
    globalSignal: "英文产品 · Web 自助 · 全球创作者",
    accent: "#e15b35",
  },
  {
    id: "anythingllm",
    name: "AnythingLLM",
    maker: "Timothy Carambat 与 Mintplex Labs",
    origin: "美国小团队 · 全球开源社区",
    productUrl: "https://anythingllm.com/",
    sourceUrl: "https://www.ycombinator.com/companies/anythingllm",
    category: "本地 AI 工作空间",
    tagline: "在桌面端或自托管环境中连接文档、模型和 Agent，默认本地运行并保留完整数据控制权。",
    bestFor: "个人知识、私有部署与本地 Agent",
    teamLabel: "4 人核心团队 + 开源社区",
    businessModel: "免费开源 + 云端与专业版",
    globalSignal: "跨平台 · 多语言 · 64K+ GitHub Stars",
    accent: "#1f9d77",
  },
  {
    id: "dyad",
    name: "Dyad",
    maker: "Will Chen",
    origin: "独立创作者主导 · 全球开源用户",
    productUrl: "https://www.dyad.sh/",
    sourceUrl: "https://www.dyad.sh/",
    category: "本地 AI 应用开发",
    tagline: "在本地用任意模型生成全栈应用，保留源码所有权，并自由连接 GitHub、Supabase 与部署平台。",
    bestFor: "重视隐私、模型选择与代码所有权的开发者",
    teamLabel: "创始人主导的开源项目",
    businessModel: "免费开源 + Pro 订阅",
    globalSignal: "Mac/Windows · BYOK · 20K+ GitHub Stars",
    accent: "#2563eb",
  },
  {
    id: "aidbase",
    name: "Aidbase",
    maker: "Simon Høiberg 与小团队",
    origin: "丹麦创始团队 · 全球 SaaS 客户",
    productUrl: "https://www.aidbase.ai/",
    sourceUrl: "https://www.indiehackers.com/post/how-simon-hoiberg-made-5-000-mrr-with-his-new-ai-saas-9d2ab1eefc",
    category: "AI 客户支持",
    tagline: "把聊天机器人、知识库、工单和邮件支持整合成可嵌入 SaaS 的自动化客服系统。",
    bestFor: "SaaS 创业公司与精简支持团队",
    teamLabel: "创始人主导的小团队",
    businessModel: "7 天免费试用 + B2B 订阅",
    globalSignal: "英文产品 · 在线注册 · 多渠道集成",
    accent: "#0ea5a8",
  },
  {
    id: "meerkats",
    name: "Meerkats",
    maker: "Santanu Dasgupta",
    origin: "印度创始人主导 · 全球 D2C",
    productUrl: "https://meerkats.ai/",
    sourceUrl: "https://www.indiehackers.com/post/tech/growing-an-ai-orchestration-platform-to-3k-mrr-in-4-weeks-gK3zYDqQjXYG9ANwmxzA",
    category: "AI 广告与利润分析",
    tagline: "连接广告、商店、订单与成本数据，由 AI Agent 识别真实获客成本并提出可审批的优化动作。",
    bestFor: "Shopify、D2C 品牌与增长团队",
    teamLabel: "创始人主导的小团队",
    businessModel: "免费接入 + B2B 订阅",
    globalSignal: "英文产品 · Web 自助 · 跨广告平台",
    accent: "#f59e0b",
  },
  {
    id: "superwhisper",
    name: "Superwhisper",
    maker: "Neil Chudleigh 与团队",
    origin: "独立创始人成长的小团队 · 全球用户",
    productUrl: "https://superwhisper.com/",
    sourceUrl: "https://deepgram.com/podcast/aiminds-014-neil-chudleigh-creator-and-founder-of-superwhisper",
    category: "AI 语音输入",
    tagline: "在系统任意应用中把语音实时转成经过格式化的文字，并支持本地模型、会议与 Agent 工作流。",
    bestFor: "写作、编程、会议与无障碍输入",
    teamLabel: "独立创始人起步的产品团队",
    businessModel: "免费层 + Pro 与终身授权",
    globalSignal: "Mac/Windows/iOS · 本地模型 · 全球下载",
    accent: "#8b5cf6",
  },
  {
    id: "genvibe",
    name: "GenVibe",
    maker: "Balram Kapoor",
    origin: "印度独立创始人 · 全球开发者",
    productUrl: "https://genvibe.pro/",
    sourceUrl: "https://www.indiehackers.com/post/how-i-got-500-devs-to-try-my-ai-app-builder-in-a-week-solo-founder-no-ads-ziE6XkhduF9WPxGSaZ0v",
    category: "AI Web 与移动开发",
    tagline: "从提示词、Figma 或截图生成 Web 和 React Native 应用，支持预览、源码导出与一键部署。",
    bestFor: "独立开发者、设计师与移动应用原型",
    teamLabel: "独立创始人主导",
    businessModel: "免费点数 + 订阅与充值",
    globalSignal: "英文产品 · Web 自助 · 代码可导出",
    accent: "#ec4899",
  },
] as const;

export const INTERNATIONAL_PRODUCT_COUNT = MAINSTREAM_AI_PRODUCTS.length + INDIE_AI_PRODUCTS.length;
