import type { SignalItem } from "@/types/signal";

export { SIGNALS_LAST_VERIFIED } from "@/lib/signals/constants";

export const SIGNAL_ITEMS = ([
  {
    id: "google-play-us-third-party-catalog",
    title: "Google Play 已向美国第三方应用商店开放应用目录",
    company: "Google Play",
    date: "2026-07-22",
    category: "出海",
    impact: "平台与规则",
    summary: "除非开发者选择退出，Google Play 已开始把应用商店资料提供给参与计划的美国第三方 Android 应用商店。",
    whyItMatters: "第三方商店可以复用 Play 的应用目录资料。对出海 App 而言，商店覆盖、退出机制、交易归因和平台服务费会进入同一套分发设计。",
    nextStep: "关键变量包括是否进入第三方目录、不同商店的版本与素材同步，以及 10 月 1 日起适用的交易和成功下载报告与服务费规则。",
    facts: [
      "Google 于 6 月 22 日向开发者说明目录提供与退出机制。",
      "Play Catalog Access 与 Third-party App Store on Play 均于 7 月 22 日在美国生效。",
      "加入美国外部内容链接或替代计费计划的开发者，自 10 月 1 日起需要报告交易和成功下载，并支付相应服务费。",
    ],
    tags: ["美国", "Android", "应用商店", "分发", "替代计费"],
    sourceLabel: "Google Play Console Help",
    sourceUrl: "https://support.google.com/googleplay/android-developer/answer/15582165?hl=en",
    relatedToolIds: [],
    market: "美国",
    focus: ["分发", "计费", "归因"],
    applicableTo: ["Android App", "订阅产品"],
    featured: true,
  },
  {
    id: "instagram-reels-ai-translation-expansion",
    title: "Instagram Reels AI 翻译新增日、韩、法、德、意五种语言",
    company: "Meta",
    date: "2026-07-14",
    category: "KOL",
    impact: "KOL 与渠道",
    summary: "Reels 的 AI 翻译新增法语、德语、意大利语、日语和韩语，可翻译音频、生成配音，并可选择口型同步。",
    whyItMatters: "同一条创作者素材可以更低成本覆盖日本、韩国和欧洲主要市场，KOL 合作从单市场制作逐步转向多语言复用。",
    nextStep: "关键变量是品牌术语准确度、口型与语气自然度、文化语境，以及不同语言版本的完播与转化差异。",
    facts: [
      "新增语言为法语、德语、意大利语、日语和韩语。",
      "功能包括 AI 音频翻译与配音，并可选择口型同步。",
      "该能力延续既有英语、西班牙语、印地语、葡萄牙语及多种印度语言支持。",
      "该功能面向 Meta AI 已开放国家和地区内的公开 Instagram 账号。",
    ],
    tags: ["Instagram", "Reels", "本地化", "日韩", "欧洲"],
    sourceLabel: "Meta Newsroom",
    sourceUrl: "https://about.fb.com/news/2025/10/discover-reels-around-world-meta-ai-translation/",
    relatedToolIds: ["meta-ai"],
    market: "日 / 韩 / 法 / 德 / 意语内容",
    focus: ["内容本地化", "创作者营销"],
    applicableTo: ["消费级 App", "创作者工具"],
    featured: true,
  },
  {
    id: "google-play-new-service-fees-2026",
    title: "Google Play 新费率已在欧洲经济区、英国和美国上线",
    company: "Google Play",
    date: "2026-06-30",
    category: "出海",
    impact: "平台与规则",
    summary: "Google Play 的新服务费框架已在欧洲经济区、英国和美国进入首批阶段，交易类型、安装批次与参与计划会共同影响费率。",
    whyItMatters: "同一款订阅产品在不同地区、安装批次和计费路径下可能出现不同平台成本，全球统一价格不再等于统一毛利。",
    nextStep: "关键变量包括经常性与非经常性交易、首个 100 万美元收入档与计费方式；Apps Experience / Games Level Up 计划及澳洲、日本下一阶段均从 9 月 30 日开始。",
    facts: [
      "新框架于 6 月 30 日在欧洲经济区、英国和美国首批上线。",
      "标准新安装的非经常性交易服务费为 20%，经常性交易为 10%，另加适用计费费。",
      "Apps Experience 与 Games Level Up 计划于 9 月 30 日在首批三地可用；澳洲和日本也在同日进入下一阶段。",
    ],
    tags: ["Google Play", "平台费", "订阅", "美国", "欧洲"],
    sourceLabel: "Google Play Console Help",
    sourceUrl: "https://support.google.com/googleplay/android-developer/answer/16954621?hl=en",
    relatedToolIds: [],
    market: "欧洲经济区 / 英国 / 美国",
    focus: ["定价", "平台费", "毛利"],
    applicableTo: ["Android App", "订阅产品"],
    featured: true,
  },
  {
    id: "android-developer-verification-first-markets",
    title: "Android 开发者验证将先在巴西、印尼、新加坡与泰国生效",
    company: "Android",
    date: "2026-06-18",
    category: "出海",
    impact: "平台与规则",
    summary: "9 月 30 日起，巴西、印度尼西亚、新加坡和泰国的认证 Android 设备，常规安装要求应用由已验证开发者注册。",
    whyItMatters: "首批市场同时覆盖 Google Play 与多家手机厂商商店，多商店分发也需要统一处理组织身份、包名和签名注册。",
    nextStep: "关键变量是组织账户的 D-U-N-S 与组织材料、开发者身份、包名和签名清单，以及不同商店的账号归属与版本一致性。",
    facts: [
      "首批强制市场为巴西、印度尼西亚、新加坡和泰国。",
      "规则于 2026 年 9 月 30 日在首批四国生效，并计划从 2027 年起逐步扩展到全球。",
      "首批覆盖 Google Play、HONOR、OPPO、Samsung、Transsion、vivo 与 Xiaomi 等分发渠道。",
      "高级用户仍可在一次性风险确认后，通过高级流程安装未注册应用；ADB 安装不受影响。",
    ],
    tags: ["Android", "开发者验证", "巴西", "东南亚", "多商店"],
    sourceLabel: "Android Developers Blog",
    sourceUrl: "https://developer.android.com/blog/posts/android-developer-verification-building-a-safer-ecosystem-together",
    relatedToolIds: [],
    market: "巴西 / 印尼 / 新加坡 / 泰国",
    focus: ["身份验证", "多商店分发", "合规"],
    applicableTo: ["Android App", "移动游戏"],
    featured: true,
    deadline: "2026-09-30",
    actionLabel: "9 月 30 日首批生效",
  },
  {
    id: "youtube-auto-dubbing-27-languages",
    title: "YouTube 自动配音覆盖 27 种语言",
    company: "YouTube",
    date: "2026-05-15",
    category: "KOL",
    impact: "KOL 与渠道",
    summary: "YouTube 自动配音体系已覆盖 27 种语言，其中 8 种支持 Expressive Speech；具体目标语言取决于视频的原始语言。",
    whyItMatters: "创始人和 KOL 的中文口播目前可以更低成本测试英语内容；其他语言方向需要按 YouTube 的原始语言支持矩阵分别确认。",
    nextStep: "关键变量包括品牌术语审校、语言自然度、原声与配音版本的观看时长，以及不同市场的搜索与推荐表现。",
    facts: [
      "自动配音体系现已覆盖 27 种语言，但并非任意语言之间都能互译。",
      "其中 8 种语言支持 Expressive Speech。",
      "YouTube 表示，2025 年 12 月每天有超过 600 万观众观看至少 10 分钟自动配音内容。",
      "中文和繁体中文原声目前支持自动配音为英语。",
    ],
    tags: ["YouTube", "自动配音", "内容本地化", "创始人 IP"],
    sourceLabel: "YouTube Official Blog",
    sourceUrl: "https://blog.youtube/creator-and-artist-stories/youtube-auto-dubbing-explained/",
    relatedToolIds: [],
    market: "全球",
    focus: ["多语言内容", "视频分发"],
    applicableTo: ["创始人 IP", "教育与工具产品"],
    featured: true,
  },
  {
    id: "elevenlabs-global-creator-payouts",
    title: "ElevenLabs 把语音 AI 商业化延伸到全球创作者分账",
    company: "ElevenLabs",
    date: "2026-05-07",
    category: "产品",
    impact: "产品案例",
    summary: "ElevenLabs 在扩展按量计费的同时，通过全球语音演员市场处理授权、使用收益与跨地区分账。",
    whyItMatters: "语音 AI 的全球化不只取决于多语言模型，还包括内容授权、创作者收益分配、地区合规和按量计费。",
    nextStep: "案例观察维度包括语音授权链路、创作者身份验证、分账与税务、本地支付，以及用量增长后的计费模型。",
    facts: [
      "Stripe 披露 ElevenLabs 的年经常性收入已超过 5 亿美元。",
      "其全球市场允许语音演员授权声音，并按实际使用获得收入。",
      "Stripe Connect 处理跨地区入驻、付款与合规，产品侧还支持印度 UPI 等本地支付。",
    ],
    tags: ["语音 AI", "创作者经济", "分账", "按量计费"],
    sourceLabel: "Stripe Newsroom",
    sourceUrl: "https://stripe.com/newsroom/news/elevenlabs-and-stripe",
    relatedToolIds: ["elevenlabs"],
    market: "全球",
    focus: ["创作者供给", "分账", "本地支付"],
    applicableTo: ["生成式内容平台", "API 产品"],
  },
  {
    id: "tiktok-pulse-tastemakers",
    title: "TikTok Pulse Tastemakers 增加创作者邻接投放",
    company: "TikTok",
    date: "2026-03-24",
    category: "KOL",
    impact: "KOL 与渠道",
    summary: "品牌可以选择符合条件的创作者，让广告与所选创作者对齐，把 KOL 内容与媒体投放放进同一套方案。",
    whyItMatters: "海外 KOL 合作正在从单条内容采购延伸到创作者内容、品牌安全和付费放大的组合评估。",
    nextStep: "关键变量包括创作者受众匹配、内容邻接环境、品牌安全、自然传播与付费投放的增量，以及转化归因。",
    facts: [
      "TikTok 在 NewFronts 2026 公布 Pulse Tastemakers。",
      "品牌可选择符合条件的创作者，让 Pulse 广告与所选创作者对齐。",
      "同期发布的品牌广告能力还包括 Logo Takeover、Prime Time 与 TopReach。",
    ],
    tags: ["TikTok", "创作者营销", "品牌投放", "美国"],
    sourceLabel: "TikTok Newsroom",
    sourceUrl: "https://newsroom.tiktok.com/newfronts-26-tiktok-unveils-new-high-impact-ad-solutions?lang=en",
    relatedToolIds: [],
    market: "美国（其他市场以 TikTok Ads 为准）",
    focus: ["KOL 投放", "品牌安全", "归因"],
    applicableTo: ["消费级 App", "创作者工具"],
  },
  {
    id: "youtube-creator-partnerships-2026",
    title: "YouTube Creator Partnerships 统一品牌找人、投放与衡量",
    company: "YouTube",
    date: "2026-03-23",
    category: "KOL",
    impact: "KOL 与渠道",
    summary: "YouTube 将 BrandConnect 升级为 Creator Partnerships，并接入 YouTube Studio、Google Ads 与 Display & Video 360。",
    whyItMatters: "海外 KOL 合作可以从手工找达人，转向平台内的发现、付费放大和效果衡量，更适合多市场复制。",
    nextStep: "关键变量包括受众与产品匹配、自然内容表现、付费放大成本，以及 Brand Lift、Search Lift 与 Conversion Lift。",
    facts: [
      "Creator Partnerships 直接集成 YouTube Studio、Google Ads 和 Display & Video 360。",
      "Gemini 辅助品牌从 300 多万 YouTube Partner Program 创作者中发现合作对象。",
      "衡量能力包括 Brand Lift、Search Lift 与 Conversion Lift。",
    ],
    tags: ["YouTube", "Creator Partnerships", "KOL", "效果衡量"],
    sourceLabel: "YouTube Official Blog",
    sourceUrl: "https://blog.youtube/news-and-events/youtube-creator-partnerships-newfronts-2026/",
    relatedToolIds: [],
    market: "可用市场以 YouTube / Google Ads 为准",
    focus: ["达人发现", "付费放大", "效果衡量"],
    applicableTo: ["消费级 App", "B2B SaaS"],
  },
  {
    id: "gamma-global-checkout-local-payments",
    title: "Gamma 用 30+ 语言结账与本地支付支撑全球收入",
    company: "Gamma",
    date: "2026-01-27",
    category: "产品",
    impact: "产品案例",
    summary: "据 Stripe 披露，Gamma 已有 7000 万用户、年经常性收入超过 1 亿美元，且多数收入来自美国以外。",
    whyItMatters: "这是 AI SaaS 从页面翻译走向完整商业本地化的样本：语言、币种、支付方式和企业合同需要一起工作。",
    nextStep: "案例观察维度包括 30 多种语言结账、本地币种展示、印度 UPI、欧洲 SEPA Debit，以及自助订阅与企业发票的组合。",
    facts: [
      "据 Stripe 披露，Gamma 有 7000 万用户，年经常性收入超过 1 亿美元。",
      "Gamma 的多数收入来自美国以外。",
      "其结账支持 30 多种语言，并结合印度 UPI、欧洲 SEPA Debit、本地货币与企业发票。",
    ],
    tags: ["AI SaaS", "本地支付", "结账本地化", "全球收入"],
    sourceLabel: "Stripe Newsroom",
    sourceUrl: "https://stripe.com/newsroom/news/gamma-and-stripe",
    relatedToolIds: ["gamma"],
    market: "全球",
    focus: ["结账本地化", "支付", "企业销售"],
    applicableTo: ["AI SaaS", "订阅产品"],
    featured: true,
  },
  {
    id: "higgsfield-global-creator-marketplace",
    title: "Higgsfield 把 AI 视频产品扩展成全球创作者市场",
    company: "Higgsfield",
    date: "2026-01-20",
    category: "产品",
    impact: "产品案例",
    summary: "据 Stripe 披露，Higgsfield 正在扩展全球创作者市场，结账页可在 150 个国家显示本地货币并接入多地支付方式。",
    whyItMatters: "AI 产品从订阅升级为创作者供给平台后，商业基础设施会从收款扩展到身份验证、分账、税务和区域合规。",
    nextStep: "案例观察维度包括创作者入驻与分账、本地币种、巴西 Pix、日韩钱包、稳定币，以及不同地区的税务和合规责任。",
    facts: [
      "据 Stripe 披露，Higgsfield 在两个月内将年化收入从 1 亿美元增至 2 亿美元。",
      "新市场主要面向来自美国、欧洲、英国、韩国、日本和加拿大的创作者。",
      "结账页可在 150 个国家显示本地货币，并支持 Pix、Kakao Pay、Naver Pay、微信支付与稳定币等方式。",
    ],
    tags: ["AI 视频", "创作者市场", "本地支付", "全球分账"],
    sourceLabel: "Stripe Newsroom",
    sourceUrl: "https://stripe.com/newsroom/news/higgsfield-and-stripe",
    relatedToolIds: [],
    market: "全球",
    focus: ["创作者市场", "本地支付", "跨境分账"],
    applicableTo: ["AI 视频", "双边平台"],
  },
] satisfies SignalItem[]).sort((left, right) => right.date.localeCompare(left.date));

export function getSignalItem(id: string) {
  return SIGNAL_ITEMS.find((item) => item.id === id) ?? null;
}

export function getRelatedSignals(item: SignalItem, limit = 3) {
  return SIGNAL_ITEMS.filter(
    (candidate) =>
      candidate.id !== item.id &&
      (candidate.company === item.company || candidate.category === item.category),
  ).slice(0, limit);
}
